source 'https://rubygems.org'

gem 'sinatra',         '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma',            '~> 6.0'
gem 'activerecord',    '~> 8.0'
gem 'sqlite3',         '~> 2.0'

gem 'rake'

group :test do
  gem 'minitest',              '~> 5.0'
  gem 'minitest-spec-context', '~> 0.0.3'
  gem 'rack-test',             '~> 2.0'
  gem 'webmock',               '~> 3.0'
end
